[package]
name = "cast_iron"
version = "0.4.4"
authors = ["CJ McAllister <cjm571@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7.3"
uuid = { version = "0.8.1", features = ["v4"] }