[package]
name = "cast_iron"
version = "0.8.1"
authors = ["CJ McAllister <cjm571@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7.3"
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
uuid = { version = "0.8.1", features = ["v4"] }