name: Default-Workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustup:
    runs-on: self-hosted

    steps:
      - name: Update
        run: rustup update
        

  checkout:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Display installed toolchains
      run: rustup toolchain list

    - name: Build debug target
      run: cargo build --verbose

    - name: Lint via `clippy`
      run: cargo clippy